### ISSUE TITLE
'异步编程：使用 stream' page issue

### ISSUE THREAD

**Issue by chenglu** [cfug/dartlang-cn#126]
Page URL: https://dart.dev/tutorials/language/streams
Page source: https://github.com/cfug/dartlang-cn/tree/master/src/_tutorials/language/streams.md

Description of issue:

![image](https://user-images.githubusercontent.com/2258420/64403708-2e39c100-d0ac-11e9-9d09-b06aa5615c57.png)

**Comment by AigeStudio** [comment]
Resolved

**Comment by chenglu** [comment]
Thanks!
