### ISSUE TITLE
希望整合社区的翻译文档，不要重复翻译

### ISSUE THREAD

**Issue by lishizhi** [cfug/dartlang-cn#2]
目前已经出现了多个dart和flutter的翻译项目，有一些已经许久不更新了，由于项目太多很多社区的贡献者不知道去哪里贡献代码，这个dart项目翻译得不错[site-www-cn](https://github.com/dartchina/site-www-cn)，希望社区能整合一下翻译项目，帮助更多像我这样英文不好的人。

**Comment by chenglu** [comment]
👍谢谢提出，最近在忙着 Flutter 在 GMTC 的演讲等工作忽略了 Issue。
期待我们一起共同探讨！
