### ISSUE TITLE
希望能够整合 DartChina 的 dartlang 中文翻译到 CFUG

### ISSUE THREAD

**Issue by amisare** [cfug/dartlang-cn#3]
本人目前在组织和翻译 dartlang 官网的中文版 [dartdoc](http://www.dartdoc.cn) ，站点 dartlang 官网收录并作为中文版本的链接。项目已持续维护近一年左右，并保持与官方同步，最新版本处在翻译过程中，未全部完成。
 
Issue #2 的提交者由 github 联系本人得知 CFUG 组织，并建议本人能够将 [site-www-cn](https://github.com/dartchina/site-www-cn) 合并到 CFUG 。今天和 DartChina 组内成员沟通商议，得到了组员的积极支持，希望能够合并到 CFUG ，由此能够更好的支持 Dart 的推广和发展。

以上。

**Comment by chenglu** [comment]
赞，抱歉最近在忙着 Flutter 的活动没有看 Issue，错过了消息，深感抱歉。
没问题，让我们一起商量一下，如何共同协作完成 Dart 的中文文档在国内的发布，以此更好的支持 Dart 的普及和发展。

**Comment by chenglu** [comment]
@amisare 按照网站联系方式加了微信，保持联系。

**Comment by chenglu** [comment]
今晚跟 @amisare 同学一起碰面聊天非常愉快，接下来我们会共同完成文档网站的合并。

**Comment by amisare** [comment]
> 今晚跟 @amisare 同学一起碰面聊天非常愉快，接下来我们会共同完成文档网站的合并。

非常高兴能为  Dart 在中国的推广和发展贡献自己的力量😁。

**Comment by chenglu** [comment]
我大致列一下 Todo List，完成之后再 close 这个 issue:

文档迁移：
 - [ ] 双语对照工具 Translator 的工具更新、部署 (owner: @asnowwolf)
 - [ ] 运营志愿者明确文档的迁移计划 (owner: @chenglu)
 - [ ] 运营志愿者花一周的时间完成需要迁移部分文档的迁移 (owner: @Jin-zz)

站点部署：
 - [ ] dartdoc.cn 绑定新的 repo，用于已 merge 文档的实时预览页面 (owner: @chenglu, collaborator: @amisare)
 - [ ] 新域名洽谈中，新域名将用于部署 release 文档，待本项目完结，dartdoc.cn 跳转到新域名 (owner: @chenglu)

项目启动：
 - [ ] 立项，完成 wiki 说明文档等 (owner: @chenglu, collaborator: @inferjay)
 - [ ] 发布迁移文档部分的 review 任务（通过 Issues）(owner: @cfug-dev, collaborators: @Jin-zz, @chenglu, @wanglin6600, etc)
 - [ ] 发布未翻译文档部分的翻译任务（通过 Issues）(owner: @cfug-dev, collaborators: @Jin-zz, @chenglu, @wanglin6600, etc)

以上，如果有任何的问题欢迎随时提出，感谢～

**Comment by chenglu** [comment]
CI broken 问题已经解决：
问题出现在 ```<?code-excerpt```，这个里面不能出现中文字符，我们翻译了一些注释导致了这个问题。

已经 [最近 commit](https://github.com/cfug/dartlang-cn/commit/dfd9bff1b3a52c004b60fc200fccd0f96d6b29e8) 里更新 src/samples/index.md 文档。

**Comment by chenglu** [comment]
7/8 update:
CI 调整完毕，但是双语显示有问题，需要再调校一下。
dartdoc 文档迁移合并完毕，部署出了一些困难，需要再等一下。

**Comment by chenglu** [comment]
wiki 和协作文档正在进行中，域名洽谈出现了一些延迟的情况，需要稍等一下。

**Comment by chenglu** [comment]
dart.cn 已经拿下！用于生产环境中的 production 域名，想在 9 月中发布，时间估计有点赶，因为 GD 的域名可能设置了 60 天不能转出。

**Comment by chenglu** [comment]
域名已经完成转移和配置，也基本搭建起来了测试项目 https://dart.cn，可以开启新的翻译项目了，再次感谢 @amisare 以及所有在项目启动阶段帮忙的同学们，预祝项目可以按期完成，本 Issue 关闭。
