### ISSUE TITLE
Libraries and packages - 库和 package

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dartlang-cn#63]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/server/libraries.md

文档预览地址：http://www.dartdoc.cn/server/libraries

建议完成天数：3 ~ 5 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by Jin-zz** [comment]
@AigeStudio 辛苦啦 
翻译已成功认领和登记！感谢！
