### ISSUE TITLE
Get started - 起步教程：编写命令行和服务端应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dartlang-cn#67]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/_tutorials/server/get-started.md

文档预览地址：http://www.dartdoc.cn/tutorials/server/get-started

建议完成天数：3 ~ 5 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by Jin-zz** [comment]
再次感谢 @AigeStudio ！
翻译已成功认领和登记
