### ISSUE TITLE
Overview - 命令行和服务端应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dartlang-cn#68]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/server/index.md

文档预览地址：http://www.dartdoc.cn/server/

建议完成天数：1 ~ 2 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by Jin-zz** [comment]
感谢 @AigeStudio 的时间！辛苦啦
已成功认领和登记！
