### ISSUE TITLE
Mobile apps - 开发移动应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dartlang-cn#69]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/mobile.md

文档预览地址：http://www.dartdoc.cn/mobile

建议完成天数：1 ~ 2 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by Jin-zz** [comment]
感谢 @AigeStudio ！辛苦辛苦啦

**Comment by hayley1643** [comment]
感谢 @AigeStudio 的翻译
