### ISSUE TITLE
Streams - 异步编程：使用 stream

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dartlang-cn#70]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/_tutorials/language/streams.md

文档预览地址：http://www.dartdoc.cn/tutorials/language/streams

建议完成天数：10 ~ 14天

**Comment by AigeStudio** [comment]
翻译中

**Comment by Jin-zz** [comment]
感谢 @AigeStudio 辛苦啦，翻译已成功认领和登记
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！

**Comment by Jin-zz** [comment]
翻译已完成 感谢 @AigeStudio ！
