### ISSUE TITLE
Using JSON - 在 Dart 里使用 JSON

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dartlang-cn#71]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/_guides/json.md

文档预览地址：http://www.dartdoc.cn/guides/json

建议完成天数：1 ~ 2 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by Jin-zz** [comment]
感谢 @AigeStudio ！
翻译已成功认领和登记！辛苦啦
