### ISSUE TITLE
Creating streams - 在 Dart 里使用 streams

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dartlang-cn#84]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/_articles/libraries/creating-streams.md

文档预览地址：http://www.dartdoc.cn/articles/libraries/creating-streams

建议完成天数：10 ~ 14 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by Jin-zz** [comment]
抱歉回复晚了
翻译已成功认领和登记！感谢 @AigeStudio ！

**Comment by Jin-zz** [comment]
该篇翻译已完成 辛苦啦
