### ISSUE TITLE
Tour - Dart 开发语言概览 - [润稿]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dartlang-cn#95]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/_guides/language/language-tour.md

文档预览地址：http://www.dartdoc.cn/guides/language/language-tour

建议完成天数：21 ~ 30 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by Jin-zz** [comment]
感谢 @AigeStudio 的时间，翻译已成功认领和登记！
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！

**Comment by AigeStudio** [comment]
貌似代码块中的英文注释按隔行翻译的格式不能将原英文注释隐藏，所以示例代码中的英文注释部分我将原英文删除了替换成中文。所幸这些含有注释的语句块并不是很多。

**Comment by AigeStudio** [comment]
示例代码中可以将其转换为中文示例的我也将其转换成中文示例了，比如在描述 Dart 字符串的示例中，原示例为：

`var s = 'This is a string.'`

中文我则将之更改为：

`var s = '这是一个字符串。'`

不知是否符合翻译规范。

**Comment by AigeStudio** [comment]
这篇文章的 Markdown 原稿有多处合并冲突被直接合并了，合并 commit ID 为：f26718e0e9d8b8ecf13131688ad7d0ab11a6c3ec。我已经解决掉这些冲突。

**Comment by Jin-zz** [comment]
感谢译者的贡献 该篇翻译已完成
